name: Publish Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      repository:
        description: "Package repository to publish to"
        required: true
        default: "testpypi"
        type: choice
        options:
          - testpypi
          - pypi
      ref:
        description: "Git ref to build from for manual runs"
        required: false
        type: string

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml
    with:
      ref: inputs.ref
  
  publish-testpypi:
    name: Publish To TestPyPI
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.repository == 'testpypi' }}
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/piethorn
    permissions:
      id-token: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    name: Publish To PyPI
    needs: build
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.repository == 'pypi') }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/piethorn
    permissions:
      id-token: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Create GitHub Release
    needs: publish-pypi
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.repository == 'pypi' && startsWith(inputs.ref, 'v')) }}
    permissions:
      contents: write
    uses: ./.github/workflows/release.yml
    with:
      ref: inputs.ref
